### ISSUE TITLE
swig build warning fprops

### ISSUE THREAD

**Issue by ba22-cmu** [ascend4/ascend4#8]
swig -o models/johnpye/fprops/python/fprops_wrap.c -python models/johnpye/fprops/python/fprops.i^
models/johnpye/fprops/python/fprops.i:71: Warning 303: %extend defined for an undeclared class ReferenceState.

It looks like RS is defined in filedata.h, but I'm not sure what's going on with swig in detail. @jdpipe

**Comment by jdpipe** [comment]
fixed in [e20f6b9](https://github.com/ascend4/ascend4/commit/e20f6b9c0b05b96982eb3a32dad1db3aeed1dfb8)

**Comment by jdpipe** [comment]
fixed in commit e20f6b9
